utils::globalVariables(unique(c(
    # bvq_logs: 
    "code",
    "date_started",
    "complete_items", 
    "date_birth", 
    "date_sent", 
    "id_db", 
    "language", 
    "progress",
    "response", 
    "study", 
    "time_stamp", 
    # bvq_participants: 
    "code", 
    "date_birth", 
    "date_sent",
    "date_test", 
    "link", 
    # bvq_responses: 
    "code",
    "date_birth",
    "item", 
    "time_stamp", 
    # bvq_responses : <anonymous>: 
    "postcode", 
    "verbose",
    # bvq_norms:
    "pool", 
    "dominance", 
    "understands", 
    "produces", 
    "label",
    ".sum", 
    "item_dominance",
    "age", 
    ".prop", 
    ".n",
    # bvq_vocabulary:
    "understands", 
    "produces", 
    "pool",
    "is_both",
    "is_any",
    "dominance",
    "L1",
    "L2",
    "type",
    "n_total_dominance",
    "n_total",
    "item_dominance", 
    "total_count", 
    "l1_count", 
    "l2_count", 
    "concept_count",
    "te_count", 
    "total_prop",
    "l1_prop",
    "l2_prop",
    "concept_prop",
    "te_prop",
    # fix_doe: 
    "doe_catalan",
    "doe_others",
    "doe_spanish", 
    # fix_item: 
    "item", 
    # fix_postcode: 
    "postcode", 
    # fix_study: 
    "study", 
    # import_formr2: 
    ".", 
    "age", 
    "code",
    "comments", 
    "created", 
    "created_cat",
    "created_spa",
    "date_birth",
    "demo_parent1", 
    "demo_parent2", 
    "demo_postcode",
    "ended", 
    "ended_cat", 
    "ended_spa", 
    "item", 
    "language_doe_catalan", 
    "language_doe_spanish", 
    "postcode",
    "randomisation", 
    "session",
    "sex", 
    "time_stamp", 
    # import_formr_lockdown: 
    ".", 
    "age", 
    "bl_code",
    "code",
    "created", 
    "created_cat", 
    "created_spa",
    "date_birth",
    "date_finished", 
    "demo_parent1",
    "demo_parent2", 
    "demo_postcode",
    "edu_parent1", 
    "edu_parent2", 
    "ended", 
    "ended_cat",
    "ended_spa", 
    "item",
    "language_doe_catalan", 
    "language_doe_catalan_lockdown",
    "language_doe_spanish", 
    "language_doe_spanish_lockdown",
    "postcode", 
    "session",
    "sex",
    "time_stamp", 
    # import_formr_short: 
    ".",
    "age",
    "code", 
    "created",
    "created_cat",
    "created_spa",
    "date_birth", 
    "demo_parent1", 
    "demo_parent2", 
    "demo_postcode", 
    "edu_parent1", 
    "edu_parent2", 
    "ended", 
    "ended_cat", 
    "ended_spa", 
    "item", 
    "language_doe_catalan", 
    "language_doe_spanish", 
    "postcode", 
    "session", 
    "sex", 
    "time_stamp", 
    # import_pool: 
    "cognate", 
    "include",
    "ipa", 
    "ipa_flat", 
    "te",
    # vowels
    "vowels"
)))
