#' Download formR surveys
#' 
#' @importFrom cli cli_progress_done
#' @importFrom cli cli_progress_step
#' @importFrom cli cli_progress_update
#' @importFrom cli qty
#' 
#' @param surveys Name of the surveys in the formr run.
#' @param ... Unused.
#' @author Gonzalo Garcia-Castro
#' @seealso [process_survey()]
#' @md
download_surveys <- function(surveys, ...) {
    
    n <- length(surveys)
    i <- 0
    raw <- vector(mode = "list", length = n)
    
    if (interactive()) {
        step_msg <- "Downloaded {i}/{n} {qty(i)}survey{?s}"
        cli_progress_step(msg = step_msg)
    }
    
    for (i in 1:length(surveys)) {
        raw[[i]] <- formr_raw_results(surveys[i])
        if (interactive()) cli_progress_update()
    }
    
    if (interactive()) cli_progress_done(result = "done")
    
    raw <- lapply(raw, select, -any_of("language"))
    names(raw) <- surveys
    
    return(raw)
}

#' Process survey contents
#' 
#' @importFrom stringr str_trim
#' @param raw Raw survey data, as generated by [download_survey()]
#' @param participants_tmp Participants dataset, inherited from inside the `import_*()` function environment.
#' @param survey_name character string indicating the name of the survey being processed (must be `"BL-Lockdown"`, `"BL-Short"`, or `"BL-Long-2"`).
#' @seealso [bvqdev::download_surveys()]
#' @author Gonzalo Garcia-Castro
#' @md
process_survey <- function(raw, participants_tmp, survey_name)
{
    words_cat <- select(raw[[6]], session, created_cat = created, ended_cat = ended)
    words_spa <- select(raw[[7]], session, created_spa = created, ended_spa = ended)
    
    raw_tmp <- raw %>%
        map(select, -one_of(c("created", "modified", "ended", "expired"))) %>%
        # if a single session ID has multiple entries, select most recent
        reduce(inner_join, by = join_by(session), multiple = "all") %>%
        mutate(code = fix_code(code),
               survey_name = .env$survey_name,
               version = ifelse(survey_name=="BL-Long-2",
                                survey_name, 
                                paste(survey_name, str_trim(version), sep = "-"))) %>% 
        left_join(participants_tmp, by = join_by(code)) 
    
    items_to_keep <- c("time", "code", "study", "version", "randomisation",
                       "date_birth", "date_started", "date_finished", "sex", 
                       "edu_parent1", "edu_parent2", "language_doe_catalan",
                       "language_doe_spanish", "language_doe_others")
    
    # define language of interest
    if (survey_name == "BL-Lockdown") {
        langs <- languages_lockdown1
    } else if (survey_name == "BL-Short") {
        langs <- languages_short
    } else if (survey_name == "BL-Long-2") {
        langs <- languages2
    }
    
    lang_cols <- list(catalan = langs[grep("catalan", langs)],
                      spanish = langs[grep("spanish", langs)]) %>% 
        map(function(x) paste0("language_doe_", x))
    
    # process data
    processed <- raw_tmp %>% 
        left_join(words_cat, by = join_by(session), multiple = "all") %>%
        left_join(words_spa, by = join_by(session), multiple = "all") %>%
        filter(code %in% participants_tmp$code) %>%
        drop_na(created_cat, created_spa, ended_cat, ended_spa) %>% 
        mutate(across(c(matches("created_|ended_"), date_birth), as_datetime),
               across(starts_with("language_doe"), function(x) ifelse(is.na(x), 0, x)),
               survey_name = .env$survey_name,
               date_started = get_time_stamp(., c("ended_cat", "ended_spa"), "first"),
               date_finished = get_time_stamp(., c("ended_cat", "ended_spa"), "last"),
               language_doe_catalan = get_doe(lang_cols$catalan),
               language_doe_spanish = get_doe(lang_cols$spanish),
               language_doe_others = 100 - rowSums(across(c(language_doe_catalan, language_doe_spanish)), na.rm = TRUE)) %>% 
        arrange(desc(date_finished)) %>%
        distinct(session, .keep_all = TRUE) %>%
        rename(edu_parent1 = demo_parent1,
               edu_parent2 = demo_parent2) %>%
        select(starts_with("id"),
               one_of(items_to_keep),
               starts_with("cat_"),
               starts_with("spa_")) %>% 
        pivot_longer(cols = matches("cat_|spa_"),
                     names_to = "item",
                     values_to = "response") %>%
        rename_with(function(x) gsub("language_", "", x), everything()) %>%
        mutate(language = ifelse(grepl("cat_", item), "Catalan", "Spanish"),
               sex = ifelse(sex == 1, "Male", "Female"),
               across(starts_with("edu_"), function(x) na_if(x, ""))) %>% # no included in this version
        arrange(desc(date_finished)) %>% 
        distinct(id, code, item, .keep_all = TRUE)
    
    return(processed)
}

#' Import lockdown data
#' 
#' @import dplyr
#' @importFrom formr formr_raw_results
#' @importFrom lubridate as_datetime
#' @importFrom lubridate time_length
#' @importFrom tidyr drop_na
#' @importFrom tidyr pivot_longer
#' @importFrom janitor clean_names
#' @importFrom rlang .env
#' @importFrom cli cli_alert_success
#' @param surveys Name of formr surveys from the `bilexicon_lockdown` run.
#' @param ... Unused.
#' @author Gonzalo Garcia-Castro
#' @seealso [bvqdev::import_formr_short()], [bvqdev::import_formr_2()]
#' 
#' @md
import_formr_lockdown <- function(
        
        surveys = c("bilexicon_lockdown_01_log",
                    "bilexicon_lockdown_02_welcome",
                    "bilexicon_lockdown_03_consent",
                    "bilexicon_lockdown_04_demo",
                    "bilexicon_lockdown_05_language",
                    "bilexicon_lockdown_06_words_catalan",
                    "bilexicon_lockdown_06_words_spanish"),
        ...)
{
    
    participants_tmp <- get("participants", parent.frame()) %>% 
        select(-version)
    
    # fetch responses
    raw <- download_surveys(surveys)
    raw[[1]] <- raw[[1]] %>%
        rename(code = bl_code) %>%
        mutate(code = fix_code(na_if(code, "")), # fix codes known to be wrong
               created = as_datetime(created)) %>%
        drop_na(code, ended) %>% # remove responses with no code
        fix_code_raw() %>% # fix codes known to be wrong
        filter(code %in% participants_tmp$code) %>% # remove codes not included in participants
        arrange(desc(created)) %>% 
        distinct(code, .keep_all = TRUE) # get only last response of each code
    
    processed <- process_survey(raw, participants_tmp, "BL-Lockdown")
    
    if (interactive()) {
        n_responses <- nrow(distinct(processed, code))
        cli_alert_success("BL-Lockdown updated: {n_responses} responses retrieved")
    }
    
    return(processed)
}


#' Import short
#' 
#' @import dplyr
#' @importFrom formr formr_raw_results
#' @importFrom lubridate as_datetime
#' @importFrom tidyr drop_na
#' @importFrom tidyr pivot_longer
#' @importFrom janitor clean_names
#' @importFrom rlang .env
#' @importFrom cli cli_alert_success
#' @param surveys Name of formr surveys from the `bilexicon_short` run
#' @param ... Unused.
#' @seealso [bvqdev::import_formr_lockdown()], [bvqdev::import_formr_2()]
#' @author Gonzalo Garcia-Castro
#' @md
import_formr_short <- function(
        surveys = c("bilexicon_short_01_log",
                    "bilexicon_short_02_welcome",
                    "bilexicon_short_03_consent",
                    "bilexicon_short_04_demo",
                    "bilexicon_short_05_language",
                    "bilexicon_short_06_words_catalan",
                    "bilexicon_short_06_words_spanish"), 
        ...) 
{
    
    participants_tmp <- get("participants", parent.frame()) %>%
        filter(version %in% "BL-Short") %>%
        select(-version)
    
    # fetch responses
    raw <- download_surveys(surveys)
    
    # edit Spanish inventory
    raw[[7]] <- rename_all(raw[[7]], ~ gsub("cat_", "spa_", .))
    
    # edit logs dataset
    raw[[1]] <- raw[[1]] %>%
        # fix codes known to be wrong
        mutate(code = fix_code(na_if(code, "")),
               created = as_datetime(created)) %>%
        # remove codes not inlcuded in participants
        filter(code %in% participants_tmp$code) %>%
        # get only last response of each code
        arrange(desc(created)) %>%
        distinct(code, .keep_all = TRUE) %>%
        # remove responses with no code
        drop_na(code, ended) %>%
        # fix codes known to be wrong
        fix_code_raw()
    
    processed <- process_survey(raw, participants_tmp, "BL-Short")
    
    if (interactive()) {
        n_responses <- nrow(distinct(processed, code))
        cli_alert_success("BL-Short updated: {n_responses} responses retrieved")
    }
    
    return(processed)
}

#' Import formr 2
#' 
#' @import dplyr
#' @importFrom formr formr_raw_results
#' @importFrom lubridate as_datetime
#' @importFrom tidyr drop_na
#' @importFrom tidyr pivot_longer
#' @importFrom janitor clean_names
#' @importFrom rlang .env
#' @importFrom cli cli_alert_success
#' @seealso [bvqdev::import_formr_lockdown()], [bvqdev::import_formr_short()]
#' @param surveys Name of formr surveys from the bilexicon_long2 run.
#' @param ... Unused.
#' @author Gonzalo Garcia-Castro
#' @md
import_formr2 <- function(
        surveys = c("bilexicon_01_log",
                    "bilexicon_02_welcome",
                    "bilexicon_03_consent",
                    "bilexicon_04_demo",
                    "bilexicon_05_language",
                    "bilexicon_06_words_cat",
                    "bilexicon_06_words_spa"), 
        ...) {
    
    participants_tmp <- get("participants", parent.frame()) %>%
        filter(version %in% "BL-Long",
               randomisation %in% "2") %>%
        select(-version)
    
    # fetch responses
    raw <- download_surveys(surveys)
    raw[[7]] <- rename_with(raw[[7]], function(x) gsub("cat_", "spa_", x), everything())
    raw[[1]] <- raw[[1]] %>%
        # fix codes known to be wrong
        mutate(code = fix_code(na_if(code, "")),
               created = as_datetime(created)) %>%
        # remove codes not included in participants
        filter(code %in% participants_tmp$code) %>%
        # get only last response of each code
        arrange(desc(created)) %>%
        distinct(code, .keep_all = TRUE) %>%
        # remove responses with no code
        drop_na(code, ended) %>%
        # fix codes known to be wrong
        fix_code_raw()
    
    # process data
    processed <- process_survey(raw, participants_tmp, "BL-Long-2")
    
    if (interactive()) {
        n_responses <- nrow(distinct(processed, code))
        cli_alert_success("BL-Long-2 updated: {n_responses} responses retrieved")
    }
    
    return(processed)
}
