#' Collect survey data
#'
#' @importFrom cli cli_alert_success
#' 
#' @param version Character string indicating the name fo the formr run (must be one of "bvq-1.0.1", "bvq-1.0.0", "bvq-lockdown", "bvq-long", or "bvq-short")
#' @param participants Participants dataset, as returned by [bvq::bvq_participants()]
#' @param ... Unused.
#' 
#' @author Gonzalo Garcia-Castro
#' 
#' @noRd
#' @keywords internal
#' 
#' @md
collect_survey <- function(version, 
                           participants = bvq_participants(),
                           ...) {
    
    # validate version name
    survey_options <- names(get_bvq_runs())
    if (!(version %in% survey_options)) {
        cli::cli_abort("survey must be one of {survey_options}")
    }
    
    # correct version names
    version_names <- attr(get_bvq_runs(), "versions")
    participants_tmp <- participants
    participants_tmp$version <- paste0("bvq-", participants_tmp$version)
    
    # get relevant participants
    participants_tmp <- participants_tmp[participants_tmp$version %in% version, ]
    if (version=="bvq-long") {
        participants_tmp <- participants_tmp[participants_tmp$version_list=="2", ]
    }
    participants_tmp <- participants_tmp[, colnames(participants_tmp)!="version"]
    
    # download and process survey data
    raw <- download_surveys(get_bvq_runs()[[version]]) # fetch responses
    
    # fix Spanish dataframe colnames
    colnames(raw[[7]]) <- gsub("cat_", "spa_", colnames(raw[[7]])) 
    raw[[1]] <- fix_logs_df(raw, participants_tmp) # fix logs data frame
    
    # process responses
    processed <- process_survey(raw, participants_tmp, version)
    
    if (interactive()) {
        n_responses <- nrow(distinct(processed, response_id))
        msg <- "{version} updated: {n_responses} response{?s} retrieved"
        cli::cli_alert_success(msg)
    }
    
    return(processed)
}

#' Download formr surveys
#'
#' @importFrom cli cli_progress_done
#' @importFrom cli cli_progress_step
#' @importFrom cli cli_progress_update
#' @importFrom cli qty
#' @importFrom formr formr_raw_results
#'
#' @param surveys Name of the surveys in the formr run.
#' @param verbose Should progress messages be printed in the console?
#' @param ... Unused.
#' 
#' @author Gonzalo Garcia-Castro
#' 
#' @noRd
#' @keywords internal
#' 
#' @md
download_surveys <- function(surveys, verbose = TRUE, ...) {
    n <- length(surveys)
    i <- 0
    raw <- vector(mode = "list", length = n)
    
    if (verbose && interactive()) {
        step_msg <- "Downloaded {i}/{n} {qty(i)}survey{?s}"
        cli::cli_progress_step(msg = step_msg)
    }
    
    for (i in seq_along(surveys)) {
        raw[[i]] <- formr::formr_raw_results(surveys[i])
        if (verbose && interactive()) cli_progress_update()
    }
    
    if (verbose && interactive()) cli_progress_done(result = "done")
    
    raw <- lapply(raw, select, -any_of("language"))
    names(raw) <- surveys
    
    return(raw)
}

#' Process survey contents
#'
#' @param raw Raw survey data, as generated by [bvq::download_surveys()]
#' @param participants_tmp Participants dataset, inherited from inside the `import_*()` function environment.
#' @param version character string indicating the name of the BVQ version being processed (must be `"BL-Lockdown"`, `"BL-Short"`, or `"BL-Long-2"`).
#' 
#' @importFrom dplyr if_any
#'
#' @author Gonzalo Garcia-Castro
#' 
#' @noRd
#' @keywords internal
#' 
#' @md
process_survey <- function(raw, participants_tmp, version) {
    
    # subset columns
    words_cat <- select(raw[[6]], session,
                        created_cat = created, ended_cat = ended)
    words_spa <- select(raw[[7]], session,
                        created_spa = created, ended_spa = ended)
    
    raw_tmp <- merge_surveys(raw, participants_tmp, version)
    
    items_to_keep <- c("child_id", "response_id", "time", "version", "version_list",
                       "date_birth", "date_started", "date_finished", "sex",
                       "edu_parent1", "edu_parent2", "language_doe_catalan",
                       "language_doe_spanish", "language_doe_others")
    
    # process data
    processed <- raw_tmp %>%
        select(-matches("lockdown")) %>%
        left_join(words_cat, by = join_by(session), multiple = "all") %>%
        left_join(words_spa, by = join_by(session), multiple = "all") %>% 
        dplyr::filter(response_id %in% participants_tmp$response_id,
                      !if_any(matches("created_|ended_"), is.na)) %>% 
        mutate(across(c(matches("created_|ended_"), date_birth),
                      as_datetime),
               across(starts_with("language_doe"),
                      function(x) ifelse(is.na(x), 0, x)),
               version = .env$version,
               date_started = get_time_stamp(ended_cat,
                                             ended_spa,
                                             which = "first"),
               date_finished = get_time_stamp(ended_cat,
                                              ended_spa,
                                              which = "last"),
               language_doe_catalan = get_doe(matches("catalan")),
               language_doe_spanish = get_doe(matches("spanish")),
               language_doe_others = 100 - rowSums(across(c(
                   language_doe_catalan,
                   language_doe_spanish
               )))) %>% 
        arrange(desc(date_finished)) %>%
        distinct(session, .keep_all = TRUE) %>%
        rename(edu_parent1 = demo_parent1,
               edu_parent2 = demo_parent2) %>%
        select(child_id,
               one_of(items_to_keep),
               starts_with("cat_"),
               starts_with("spa_")) %>%
        pivot_longer(cols = matches("cat_|spa_"),
                     names_to = "item",
                     values_to = "response") %>%
        rename_with(function(x) gsub("language_", "", x), everything()) %>%
        arrange(desc(date_finished)) %>%
        distinct(child_id, response_id, time, item, .keep_all = TRUE) %>% 
        mutate(language = ifelse(grepl("cat_", item), "Catalan", "Spanish"),
               response_id = fix_response_id(response_id),
               sex = ifelse(sex == 1, "Male", "Female"),
               across(starts_with("edu_"),
                      function(x) na_if(x, "")),
               date_birth = lubridate::as_date(date_birth),
               across(c(child_id, response_id, version, version_list,
                        sex, edu_parent1, edu_parent2, item, language),
                      as.character)) %>% 
        relocate(child_id, response_id, time, version, version_list, item, response, language,
                 starts_with("date_"), sex, starts_with("doe_")) %>% 
        filter(!is.na(response))
    
    return(processed)
    
}

#' Merge surveys from the same formr run
#' 
#' @param raw Raw survey data, as generated by [bvq::download_surveys()]
#' @param participants_tmp Participants dataset, inherited from inside the `import_*()` function environment.
#' @param version character string indicating the name of the BVQ version being processed (must be `"BL-Lockdown"`, `"BL-Short"`, or `"BL-Long-2"`).
#' 
#' @import dplyr
#'
#' @author Gonzalo Garcia-Castro
#' 
#' @noRd
#' @keywords internal
#' 
#' @md
merge_surveys <- function(raw, participants_tmp, version) {
    
    # merge data frames
    raw_tmp <- raw %>%
        lapply(select, -one_of(c("created", "modified", "ended", "expired"))) %>%
        # if a single session ID has multiple entries, select most recent
        reduce(inner_join, by = join_by(session), multiple = "all") %>%
        mutate(version_list = version,
               version = .env$version,
               version_list = trimws(version_list, whitespace = "[\\h\\v]")) %>%
        select(-version_list) %>% 
        left_join(participants_tmp, by = join_by(response_id))
    
    return(raw_tmp)
}



#' Fix logs dataframe
#' 
#' @param raw Named list with the contents of the surveys, as returned by [bvq::download_surveys()].
#' 
#' @author Gonzalo Garcia-Castro
#' 
#' @noRd
#' @keywords internal
#'
#' @md
fix_logs_df <- function(raw, participants_tmp) {
    
    # fix logs dataframe
    logs <- raw[[1]]
    names(logs)[names(logs) %in% c("code", "bl_code")] <- "response_id"
    # variables to correct types
    logs[c("created", "ended")] <- lapply(logs[c("created", "ended")], as.POSIXct)
    # remove if missing any critical variable
    logs$response_id <- fix_response_id(if_else(logs$response_id=="", 
                                         NA_character_, 
                                         gsub("BL", "", logs$response_id)))
    logs <- logs[!is.na(logs$response_id) & !is.na(logs$ended) & !is.na(logs$session), ]
    # fix codes known to be wrong
    logs <- fix_code_raw(logs)
    # remove codes not included in participants
    logs <- logs[logs$response_id %in% participants_tmp$response_id, ]
    # get only last response of each code
    logs <- logs[order(logs$created, decreasing = TRUE), , drop = FALSE]
    logs <- logs[!duplicated(logs$response_id), , drop = FALSE]
    
    return(logs)
    
}

