#' Generate participant information and progress for each response
#'
#' This function generates a data frame that contains
#'   participant-level information. Each row is a given participant's response
#'   and each column is a variable. The same participant will always be
#'   identified with the same `id`. The variable `time` indexes how
#'   many times a participant has been sent the questionnaire, independently of
#'   whether a response was obtained from them later.
#'
#' @import dplyr
#' @importFrom lubridate as_date
#' @importFrom lubridate today
#' @importFrom lubridate as_datetime
#'
#' @export bvq_logs
#'
#' @param responses Responses data frame, as generated by
#'   [bvq::bvq_responses()].
#' @param participants Participants data frame, as generated by
#'   [bvq::bvq_participants()].
#' @param bilingual_threshold Numeric scalar ranging from 0 to 1 indicating the
#'   minimum degree of exposure to Catalan or Spanish to consider a participant
#'   as *Monolingual*.
#' @param other_threshold Numeric scalar ranging from 0 to 1 indicating the
#'   minimum degree of exposure to languages other than Catalan and Spanish to
#'   consider a participant as *Other*.
#' @returns A data frame (actually, a [tibble::tibble] with
#'   participant-level information. Each row corresponds to a questionnaire
#'   response and each column represents a variable. The output includes the
#'   following variables:
#' * id: a character string with five digits indicating a participant's identifier in the database from the [Laboratori de Recerca en Infància](https://www.upf.edu/web/cbclab) at Universitat Pompeu Fabra. This value is always the same for each participant, so that different responses from the same participant share the same `id`.
#' * code: a character string identifying a single response to the questionnaire. This value is always unique for each response to the questionnaire, even for responses from the same participant.
#' * time: a numeric value indicating how many times a given participant has been sent the questionnaire, regardless of whether they completed it or not.
#' * study: a character string indicating the study in which the participant was invited to fill in the questionnaire. Frequently, participants that filled in the questionnaire came to the lab to participant in a study, and were then invited to fill in the questionnaire later. This value indicates what study each participant was tested in before being sent the questionnaire.
#' * version: a character string indicating what version of the questionnaire a given participant filled in. Different versions may contain a different subset of items, and the administration instructions might vary slightly (see formr questionnaire templates in the [GitHub repository(https://github.com/gongcastro/multilex)). Also, different versions were designed, implemented, and administrated at different time points (e.g., before/during/after the COVID-related lockdown).
#' * date_sent: a date value (see lubridate package) in `yyyy/mm/dd` format indicating the date in which the questionnaire was sent to participants.
#' * days_from_sent: a numeric value indicating the number of days elapsed since participants were sent the questionnaire (as indicated by `date_sent`)  and completed the questionnaire.
#' * date_birth: a date value (see lubridate package) in `yyyy/mm/dd` format indicating participants birth date.
#' * age: a numeric value indicating the number of months elapsed since participants' birth date until they filled in the last item of their questionnaire response.
#' * age_today: a numeric value indicating the number of months elapsed since participants' birth date until the present day, as indicated by [lubridate::now].
#' * months_from_last_response: a numeric value indicating the number of months elapsed since participants' last questionnaire response (as indicated  by `time_stamp`) until the present day, as indicated by [lubridate::now].
#' * edu_parent1: a character string indicating the educational attainment of one of the parents/caregivers.
#' * edu_parent2: a character string indicating the educational attainment of the other parent/caregiver, if any.
#' * dominance: a character string indicating the language of highest exposure (`"Catalan"` or `"Spanish"`), as reported by parents. If exposure is identical for both language, "Catalan" is assigned.
#' * lp: a character string indicating participants' language profile, classified using parental reports of language exposure (see `doe_spanish`, `doe_catalan`, and `doe_others`), and the thresholds passed in the `bilingual_threshold` and `other_threshold`.
#' * doe_spanish: a numeric value ranging from 0 to 1 indicating participants' daily exposure to Spanish, as estimated by parents/caregivers. This value aggregates participants' exposure to any variant of Spanish (e.g., European and American Spanish).
#' * doe_catalan: a numeric value ranging from 0 to 1 indicating participants' daily exposure to Catalan, as estimated by parents/caregivers. This value aggregates participants' exposure to any variant of Catalan (e.g., Catalan from Mallorca or Barcelona).
#' * doe_others: a numeric value ranging from 0 to 1 indicating participants' daily exposure to languages other than Spanish or Catalan, as estimated by parents/caregivers, aggregating participants' exposure to all those other languages (e.g., Norwegian, Arab, Swahili).
#' * completed: a logical value that returns `TRUE` if `progress` is 1, and `FALSE` otherwise.
#'
#' @author Gonzalo Garcia-Castro
#' 
#' @examples
#' \dontrun{
#' responses <- bvq_responses()
#' 
#' logs <- bvq_logs(responses = responses)
#' }
#' 
#' @md
bvq_logs <- function(participants = NULL,
                     responses = NULL,
                     bilingual_threshold = 0.80,
                     other_threshold = 0.10) {
  if (is.null(participants)) participants <- bvq_participants()
  if (is.null(responses)) responses <- bvq_responses(participants)

  # get n items answered by participants (depends on the questionnaire version)
  total_items <- studies %>%
    distinct(version, language, n) %>%
    summarise(
      total_items = sum(n),
      .by = version
    )

  grouping_vars <- c(
    "id", "date_birth", "time",
    "edu_parent1", "edu_parent2",
    "date_birth", "date_started", "date_finished",
    "doe_spanish", "doe_catalan",
    "doe_others", "date_birth", "code", "study",
    "version"
  )

  vars <- c(
    "code", "time", "study", "version", "age",
    "date_birth", "date_started", "date_finished",
    "duration", "dominance", "lp",
    "edu_parent1", "edu_parent2",
    "doe_spanish", "doe_catalan", "doe_others", "completed"
  )

  # generate logs
  logs <- responses %>%
    # total items to fill by each participant (varies across versions)
    summarise(
      complete_items = sum(!is.na(response)),
      .by = one_of(grouping_vars)
    ) %>%
    left_join(total_items,
      by = join_by(version)
    ) %>%
    left_join(select(participants, -c(date_birth, version)),
      by = join_by(id, time, code, study)
    ) %>%
    filter(!is.na(id)) %>%
    mutate(
      # define language profiles based on thresholds
      lp = case_when(
        doe_catalan >= bilingual_threshold ~ "Monolingual",
        doe_spanish >= bilingual_threshold ~ "Monolingual",
        doe_others > other_threshold ~ "Other",
        .default = "Bilingual"
      ),
      # define language dominance
      dominance = case_when(
        doe_catalan > doe_spanish ~ "Catalan",
        doe_spanish > doe_catalan ~ "Spanish",
        doe_catalan == doe_spanish ~ sample(c("Catalan", "Spanish"), 1)
      ),
      age = diff_in_time(date_finished, date_birth, "months"),
      duration = diff_in_time(date_finished, date_started, "days")
    ) %>%
    # compute participant's progress through the questionnaire
    mutate(
      progress = complete_items / total_items,
      completed = progress >= 0.95
    ) %>%
    # select relevant columns and reorder them
    select(id, one_of(vars)) %>%
    arrange(desc(date_finished))

  return(logs)
}
