#' Generate participant information and progress for each response
#'
#' This function generates a data frame that contains
#'   participant-level information. Each row is a given participant's response
#'   and each column is a variable. The same participant will always be
#'   identified with the same `id`. The variable `time` indexes how
#'   many times a participant has been sent the questionnaire, independently of
#'   whether a response was obtained from them later.
#'
#' @import dplyr
#' @importFrom lubridate as_date
#' @importFrom lubridate today
#' @importFrom lubridate as_datetime
#'
#' @export bvq_logs
#'
#' @param responses Responses data frame, as generated by
#'   [bvq::bvq_responses()].
#' @param participants Participants data frame, as generated by
#'   [bvq::bvq_participants()].
#' @param bilingual_threshold Numeric scalar ranging from 0 to 1 indicating the
#'   minimum degree of exposure to Catalan or Spanish to consider a participant
#'   as *Monolingual*.
#' @param other_threshold Numeric scalar ranging from 0 to 1 indicating the
#'   minimum degree of exposure to languages other than Catalan and Spanish to
#'   consider a participant as *Other*.
#' @returns A data frame (actually, a [tibble::tibble] with
#'   participant-level information. Each row corresponds to a questionnaire
#'   response and each column represents a variable. The output includes the
#'   following variables:
#' * child_id: a character string with five digits indicating a participant's identifier in the database from the [Laboratori de Recerca en Infància](https://www.upf.edu/web/cbclab) at Universitat Pompeu Fabra. This value is always the same for each participant, so that different responses from the same participant share the same `id`.
#' * response_id: a character string identifying a single response to the questionnaire. This value is always unique for each response to the questionnaire, even for responses from the same participant.
#' * time: a numeric value indicating how many times a given participant has been sent the questionnaire, regardless of whether they completed it or not.
#' * study: a character string indicating the study in which the participant was invited to fill in the questionnaire. Frequently, participants that filled in the questionnaire came to the lab to participant in a study, and were then invited to fill in the questionnaire later. This value indicates what study each participant was tested in before being sent the questionnaire.
#' * version: a character string indicating what version of the questionnaire a given participant filled in. Different versions may contain a different subset of items, and the administration instructions might vary slightly (see formr questionnaire templates in the [GitHub repository(https://github.com/gongcastro/multilex)). Also, different versions were designed, implemented, and administrated at different time points (e.g., before/during/after the COVID-related lockdown).
#' * version_list: a character string indicating the specific list of
#'   items a participant was assigned to. Only applies in the case of short
#'   versions of BVQ, such as bvq-short, bvq-long, bvq-lockdown, or bvq-1.0.0, where the
#'   list of items was partitioned into several versions.#' * date_sent: a date value (see lubridate package) in `yyyy/mm/dd` format indicating the date in which the questionnaire was sent to participants.
#' * days_from_sent: a numeric value indicating the number of days elapsed since participants were sent the questionnaire (as indicated by `date_sent`)  and completed the questionnaire.
#' * date_birth: a date value (see lubridate package) in `yyyy/mm/dd` format indicating participants birth date.
#' * age: a numeric value indicating the number of months elapsed since participants' birth date until they filled in the last item of their questionnaire response.
#' * age_today: a numeric value indicating the number of months elapsed since participants' birth date until the present day, as indicated by [lubridate::now].
#' * months_from_last_response: a numeric value indicating the number of months elapsed since participants' last questionnaire response (as indicated  by `time_stamp`) until the present day, as indicated by [lubridate::now].
#' * edu_parent1: a character string indicating the educational attainment of one of the parents/caregivers.
#' * edu_parent2: a character string indicating the educational attainment of the other parent/caregiver, if any.
#' * dominance: a character string indicating the language of highest exposure (`"Catalan"` or `"Spanish"`), as reported by parents. If exposure is identical for both language, "Catalan" is assigned.
#' * lp: a character string indicating participants' language profile, classified using parental reports of language exposure (see `doe_spanish`, `doe_catalan`, and `doe_others`), and the thresholds passed in the `bilingual_threshold` and `other_threshold`.
#' * doe_spanish: a numeric value ranging from 0 to 1 indicating participants' daily exposure to Spanish, as estimated by parents/caregivers. This value aggregates participants' exposure to any variant of Spanish (e.g., European and American Spanish).
#' * doe_catalan: a numeric value ranging from 0 to 1 indicating participants' daily exposure to Catalan, as estimated by parents/caregivers. This value aggregates participants' exposure to any variant of Catalan (e.g., Catalan from Mallorca or Barcelona).
#' * doe_others: a numeric value ranging from 0 to 1 indicating participants' daily exposure to languages other than Spanish or Catalan, as estimated by parents/caregivers, aggregating participants' exposure to all those other languages (e.g., Norwegian, Arab, Swahili).
#' * completed: a logical value that returns `TRUE` if `progress` is 1, and `FALSE` otherwise.
#'
#' @author Gonzalo Garcia-Castro
#'
#' @examples
#' \dontrun{
#' responses <- bvq_responses()
#'
#' logs <- bvq_logs(responses = responses)
#' }
#'
#' @md
bvq_logs <- function(participants = bvq_participants(),
                     responses = bvq_responses(participants),
                     bilingual_threshold = 0.80,
                     other_threshold = 0.10) {
  # check args
  arg_bil_range <- !((bilingual_threshold >= 0) & (bilingual_threshold <= 1))
  arg_bil_class <- !is.numeric(bilingual_threshold)
  if (arg_bil_range || arg_bil_class) {
    cli::cli_abort("bilingual_threshold must be numeric between 0 and 1")
  }

  arg_oth_range <- !((other_threshold >= 0) & (other_threshold <= 1))
  arg_oth_class <- !is.numeric(other_threshold)
  if (arg_oth_range || arg_oth_class) {
    cli::cli_abort("other_threshold must be numeric between 0 and 1")
  }

  if (is.null(participants)) participants <- bvq_participants()
  if (is.null(responses)) responses <- bvq_responses(participants)

  # get n items answered by participants (depends on the questionnaire version)
  total_items <- studies %>%
    distinct(version, version_list, language, n) %>%
    summarise(
      total_items = sum(n),
      .by = c(version, version_list)
    )

  grouping_vars <- c(
    "child_id", "response_id", "time",
    "date_birth",
    "edu_parent1", "edu_parent2",
    "date_birth", "date_started", "date_finished",
    "doe_spanish", "doe_catalan",
    "doe_others", "date_birth",
    "version", "version_list"
  )

  vars <- c(
    "response_id", "time", "version", "version_list", "age",
    "date_birth", "date_started", "date_finished",
    "duration", "dominance", "lp",
    "edu_parent1", "edu_parent2",
    "doe_spanish", "doe_catalan", "doe_others", "completed"
  )

  # generate logs
  logs <- responses %>%
    # total items to fill by each participant (varies across versions)
    summarise(
      complete_items = sum(!is.na(response)),
      .by = one_of(grouping_vars)
    ) %>%
    inner_join(total_items, by = join_by(version, version_list)) |>
    left_join(select(participants, -c(date_birth, version, version_list)),
      by = join_by(child_id, time, response_id)
    ) %>%
    filter(!is.na(child_id)) %>%
    mutate(
      # define language profiles based on thresholds
      lp = case_when(
        doe_others > other_threshold ~ "Other",
        doe_catalan >= bilingual_threshold ~ "Monolingual",
        doe_spanish >= bilingual_threshold ~ "Monolingual",
        .default = "Bilingual"
      ),
      # define language dominance
      dominance = case_when(
        doe_catalan > doe_spanish ~ "Catalan",
        doe_spanish > doe_catalan ~ "Spanish",
        doe_catalan == doe_spanish ~ sample(c("Catalan", "Spanish"), 1)
      ),
      age = diff_in_time(date_finished, date_birth, "months"),
      duration = diff_in_time(date_finished, date_started, "days")
    ) %>%
    # compute participant's progress through the questionnaire
    mutate(
      progress = complete_items / total_items,
      completed = progress >= 0.95
    ) %>%
    # select relevant columns and reorder them
    select(child_id, one_of(vars)) %>%
    arrange(desc(date_finished))

  return(logs)
}

#' Track a participant's response progress.
#'
#' This function prints some informative messages about a participants progress through the BVQ, and returns a vector of logical values indicating the surveys that the participant has completed.
#'
#' @importFrom lubridate as_datetime
#'
#' @export track_progress
#'
#' @param respose_id a character string identifying a single response to the questionnaire. This value is always unique for each response to the questionnaire, even for responses from the same participant.
#' @param participants Participants data frame, as generated by
#'   [bvq::bvq_participants()].
#' @param ... Arguments passed to [bvq::download_surveys].
#' @returns A logical vector indicating the surveys that the participant has completed.
#'
#' @author Gonzalo Garcia-Castro
#'
#' @examples
#' \dontrun{
#' track_progress("1911", participants, verbose = FALSE)
#' }
#'
#' @md
track_progress <- function(response_id,
                           participants = NULL,
                           ...) {
  if (is.null(participants)) participants <- bvq_participants()
  if (!is.character(response_id)) {
    cli::cli_abort("{.code response_id} must be {.type character}")
  }
  if (!(response_id %in% participants$response_id)) {
    cli::cli_abort("{.code response_id} {.val {response_id}} is not present in data")
  }
  version <- participants[participants$response_id == response_id, ]$version
  cli::cli_progress_step("Downloading responses from version {.val {version}}")
  vlist <- get_bvq_runs()
  vvalues <- attr(vlist, "versions")
  vnames <- names(vvalues)
  names(vvalues) <- NULL
  tversion <- vnames[[which(vvalues == version)]]

  sur <- download_surveys(vlist[[tversion]], ...)

  cli::cli_progress_step("Looking up status of response {.val {response_id}}")

  logs <- sur[[1]]
  logs$bl_code <- gsub("BL|CAT", "", logs$bl_code)
  logs <- fix_code_raw(logs)
  logs <- logs[logs$bl_code %in% response_id, ]
  formr_id <- logs$session

  for (fid in formr_id) {
    status <- vapply(
      lapply(sur, `[[`, "session"),
      \(x) fid
      %in% x,
      logical(1)
    )
    finished <- all(status)
    status_label <- ifelse(finished, "finished", "in progress")
    sur_now <- sur[[last(which(status))]]
    sur_now_nm <- names(sur[last(which(status))])
    sur_now_created <- as_datetime(sur_now[sur_now$session %in% fid, ]$created)
    sur_now_modified <- as_datetime(sur_now[sur_now$session %in% fid, ]$modified)
    if (is.na(sur_now_modified)) sur_now_modified <- sur_now_created

    cli::cli_h1("Session ID: {.val {fid}}")
    cli::cli_text("Response {.field {response_id}} is {.field {status_label}}")
    cli::cli_li("In {.field {sur_now_nm}} since {.val {sur_now_created}}")
    cli::cli_li("Logged in: {.val {as_datetime(logs$created)}}")
    cli::cli_li("Last activity: {.val {as_datetime(logs$created)}}")
  }
  cli::cli_progress_done(result = "done")
  return(invisible(status))
}
