#' Retrieve and update local and/or remote data from formr
#'
#' This function generates a data frame with participant's responses to each
#' item, along with some session-specific metadata. It takes `participants`
#' (the output of [bvq::bvq_participants()]) and `runs` (a character vector that can
#' take zero, one, or multiple of the following values: `"formr2"`,
#' `"formr-short"`, `"formr-lockdown"`) as arguments.
#' @importFrom stats time
#'
#' @export bvq_responses
#'
#' @param participants Participants data frame, as generated by
#'   [bvq::bvq_participants()]. If `NULL` (default), [bvq::bvq_participants()] is run.
#'
#' @returns A data frame (actually, a [tibble::tibble] containing participant's
#'   responses to each item, along with some session-specific metadata. The
#'   output includes the following variables:
#' * id: a character string with five digits indicating a participant's identifier in the database from the [Laboratori de Recerca en Infància](https://www.upf.edu/web/cbclab) at Universitat Pompeu Fabra. This value is always the same for each participant, so that different responses from the same participant share the same `id`.
#' * time: a numeric value indicating how many times a given participant has been sent the questionnaire, regardless of whether they completed it or not.
#' * code: a character string identifying a single response to the questionnaire. This value is always unique for each response to the questionnaire, even for responses from the same participant.
#' * study: a character string indicating the study in which the participant was invited to fill in the questionnaire. Frequently, participants that filled in the questionnaire came to the lab to participant in a study, and were then invited to fill in the questionnaire later. This value indicates what study each participant was tested in before being sent the questionnaire.
#' * version: a character string indicating what version of the questionnaire a given participant filled in. Different versions may contain a different subset of items, and the administration instructions might vary slightly (see formr questionnaire templates in the [GitHub repository](https://github.com/gongcastro/bvq)). Also, different versions were designed, implemented, and administrated at different time points (e.g., before/during/after the COVID-related lockdown).
#' * item: character string indicating the item identifier (e.g., `spa_mesa`). This value is unique for each item. Responses to the same item from different participants are linked by the same `item` value.
#' * response: integer indicating the participant's response to a give item: `1` if `"No"` (the participant does not understand or produce the word), `2` if "Understands" (the participants understands the word), or `3` if "Understands and Says" (the participant understands and produces the item).
#' * date_birth: a date value (see lubridate package) in `yyyy/mm/dd` format indicating participants birth date.
#' * date_started: a date value (see lubridate package) in `yyyy/mm/dd` format indicating when participants logged to the questionnaire for the first time.
#' * date_finished: a date value (see lubridate package) in `yyyy/mm/dd` format indicating when participants logged to the questionnaire for the last time.
#' * sex: a character string indicating participants' biological sex, as reported by the parents.
#' * edu_parent1: a character string indicating the educational attainment of one of the parents/caretakers.
#' * edu_parent2: a character string indicating the educational attainment of the other parent/caretaker, if any.
#' * doe_spanish: a numeric value ranging from 0 to 1 indicating participants' daily exposure to Spanish, as estimated by parents/caregivers This value aggregates participants' exposure to any variant of Spanish (e.g., European and American Spanish).
#' * doe_catalan: a numeric value ranging from 0 to 1 indicating participants' daily exposure to Catalan, as estimated by parents/caregivers This value aggregates participants' exposure to any variant of Catalan (e.g., Catalan from Majorca or Barcelona).
#' * doe_others: a numeric value ranging from 0 to 1 indicating participants' daily exposure to languages other than Spanish or Catalan, as estimated by parents/caretakers, aggregating participants' exposure to all those other languages (e.g., Norwegian, Arab, Swahili).
#' * randomisation: a character string indicating the specific list of items a participant was assigned to. Only applies in the case of short versions of BVQ, such as BL-Short, BL-Short-2 or BL-Lockdown, where the list of items was partitioned into several versions.
#'
#' @author Gonzalo Garcia-Castro
#' 
#' @examples
#' \dontrun{
#' bvq_responses()
#' }
#' 
#' @md
bvq_responses <- function(participants = NULL)
{
    
    if (is.null(participants)) participants <- bvq_participants()
    
    # retrieve data from formr
    formr.long <- collect_survey("long", participants) # formr2
    formr.lockdown <- collect_survey("lockdown", participants) # formr-lockdown
    formr.short <- collect_survey("short", participants) # formr-lockdown
    
    # merge dataframes
    formr.list <- list(formr1, formr.long, formr.short, formr.lockdown)
    responses <- do.call(rbind, formr.list)  
    
    # remove duplicated combinations of id, code, and item
    responses <- responses[!duplicated(responses[c("id", "code", "item")]), , drop = FALSE]
    
    # fix date columns
    date.cols <-  grepl("^date_", colnames(responses))
    responses[, date.cols] <- lapply(responses[, date.cols], as.Date, origin = c("1970-01-01"))
    
    # fix other variables
    responses$time <- ifelse(is.na(responses$time), 1, responses$time)
    responses$version <- trimws(responses$version, whitespace = "[\\h\\v]")
    responses <- fix_item(responses)
    responses <- fix_doe(responses)
    responses <- fix_sex(responses)
    responses$study <- ifelse(is.na(responses$study), "BiLexicon", responses$study)
    responses <- fix_id_exp(responses)
    
    # fix degree of exposure columns
    doe.cols <- grepl("^doe_", colnames(responses))
    responses[, doe.cols] <- lapply(responses[, doe.cols], function(x) x / 100)
    
    # remove rows with missing date_finished and reorder
    responses <- responses[!is.na(responses$date_finished), ]
    
    # reorder dataframe and select columns
    responses <- responses[order(responses$date_finished, decreasing = TRUE), , drop = FALSE]
    cols.keep <- c(
        "id", "time", "code", "study", 
        "version", "randomisation", 
        colnames(responses)[grepl("^date_", colnames(responses))],
        "item", "response", "sex",
        colnames(responses)[grepl("^doe_", colnames(responses))],
        colnames(responses)[grepl("^edu_", colnames(responses))]
    )
    responses <- responses[, cols.keep]
    
    return(responses)
}
