#' Generate participant information and progress for each response
#'
#' This function generates a data frame with the vocabulary of each participant
#' (keeping longitudinal data from the same participant in different rows).
#' Comprehensive and productive vocabulary sizes are computed as raw counts
#' (`*_count`) and as proportions `*_prop`.
#'
#' @export bvq_vocabulary
#'
#' @import dplyr
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr pivot_wider
#' @importFrom janitor make_clean_names
#'
#' @param participants Participants data frame, as generated by
#'   [bvq::bvq_participants()].
#' @param responses Responses data frame, as generated by
#'   [bvq::bvq_responses_vocab()].
#' @param ... <[`dynamic-dots`][rlang::dyn-dots]> Unquoted name of the
#'   variable(s) to group data into. Vocabulary metrics will be calculated by
#'   aggregating responses within the groups that result from the combination of
#'   crossing of the variables provided in `...`. These variables can refer to
#'   item properties (see [bvq::pool], e.g., `semantic_category`) or to
#'   participant properties (see [bvq::bvq_logs()], e.g., `lp`).
#' @param .scale A character vector that takes the value `"count"` and/or
#'   `"prop"`. If `"prop"` (default), vocabulary metrics are calculated as
#'   proportions. If `"count"`, vocabulary metrics are reported as counts
#'   (number of words).
#'
#' @returns A dataset (actually, a [tibble::tibble] with each participant's
#'   comprehensive and/or vocabulary size in each language. This data frame
#'   contains the following variables:
#' * child_id: a character string with five digits indicating a participant's identifier in the database from the [Laboratori de Recerca en Infància](https://www.upf.edu/web/cbclab) at Universitat Pompeu Fabra. This value is always the same for each participant, so that different responses from the same participant share the same `child_id`.
#' * response_id: a character string identifying a single response to the questionnaire. This value is always unique for each response to the questionnaire, even for responses from the same participant.
#' * age: a numeric value indicating the number of months elapsed since participants' birth date until they filled in the last item of their questionnaire response.
#' * type: a character string indicating the vocabulary type computed: `"understands"` if option "Understands" was selected, and `"produces"` if option "Understands & Says" was selected.
#' * total_count: integer indicating the number of items selected as "Understands" or "Understands and Says" in both languages.
#' * l1_count: positive integer indicating the number of items selected as "Understands" or "Understands and Says" in the dominant language (L1).
#' * l2_count: positive integer indicating the number of items selected as "Understands" or "Understands and Says" in the non-dominant language (L2).
#' * concept_count: positive integer indicating the number of translation equivalents (a.k.a. cross-language synonyms or doublets) in which  "at list one of the items was selected as "Understands" or "Understands and Says". This is a measure of the number of lexicalised concepts.
#' * te_count: positive integer indicating the number of translation equivalents (out of the total number of items the participant answered to) in which at both items was selected as "Understands" or "Understands and Says". This is a measure of the number of lexicalised concepts.
#' * total_prop: numeric value ranging from 0 to 1 (both included) indicating the proportion of items selected as "Understands" or "Understands and Says" in both languages.
#' * l1_prop: numeric value ranging from 0 to 1 (both included) indicating the proportion of of items selected as "Understands" or "Understands and Says" in the dominant language (L1).
#' * l2_prop: numeric value ranging from 0 to 1 (both included) indicating the proportion of of items selected as "Understands" or "Understands and Says" in the non-dominant language (L2).
#' * concept_prop: numeric value ranging from 0 to 1 (both included) indicating the proportion of of translation equivalents (a.k.a. cross-language synonyms or doublets) in which at least one of the items was selected as "Understands" or "Understands and Says". This is a measure of the number of lexicalised concepts.
#' * te_prop: numeric value ranging from 0 to 1 (both included) indicating the proportion of of translation equivalents (aka. cross-language synonyms or doublets) in which both items were selected as "Understands" or "Understands and Says". This is a measure of the number of lexicalised concepts.
#'   The specific subset of columns returned by [bvq::bvq_vocabulary()] depends
#'   on the elements of `...` and `.scale`.
#' * contents: list containing the items marked as acquired.
#'
#' @author Gonzalo Garcia-Castro
#'
#' @md
#'
bvq_vocabulary <- function(participants = bvq_participants(),
                           responses = bvq_responses_vocab(participants),
                           ...,
                           .scale = "prop") {
  # collect ... into a character vector for `any_of`
  dots_vctr <- as.character(match.call(expand.dots = FALSE)$`...`)

  logs <- bvq_logs(participants, responses)

  # check arguments
  possible_colnames <- list(responses, logs, bvq::pool) %>%
    purrr::map(colnames) %>%
    purrr::list_c()

  check_arg_dots(dots_vctr, .cols = possible_colnames)

  if (!all(.scale %in% c("prop", "count"))) {
    cli::cli_abort(".scale must be 'prop' and/or 'count'")
  }


  logs_tmp <- logs %>%
    dplyr::filter(child_id %in% responses$child_id) %>%
    select(child_id, response_id, dominance, any_of(dots_vctr))

  pool_tmp <- select(bvq::pool, item, te, language, any_of(dots_vctr))

  # get main dataset
  base <- responses %>%
    mutate(
      understands = response > 1,
      produces = response > 2
    ) %>%
    dplyr::filter(!is.na(response)) %>%
    select(-response) %>%
    tidyr::pivot_longer(c(understands, produces),
      names_to = "type",
      values_to = "response"
    )

  suppressMessages({
    base <- list(base, pool_tmp, logs_tmp) %>%
      # join datasets
      purrr::reduce(inner_join,
        multiple = "all",
        relationship = "many-to-many"
      ) %>%
      # define TE-by-participant properties
      mutate(item_dominance = if_else(language == dominance, "L1", "L2")) %>%
      select(
        child_id, response_id, dominance, item_dominance,
        type, te, item, any_of(dots_vctr), response
      )
  })


  # compute total denominator
  base_n <- base %>%
    distinct(pick(c(child_id, response_id, te, ...)),
      .keep_all = TRUE
    ) %>%
    count(pick(c(child_id, response_id, type, ...)),
      name = "n_total"
    ) %>%
    select(child_id, response_id, any_of(dots_vctr), n_total)

  # compute TE-wise denominator
  base_te <- base %>%
    dplyr::filter(response) %>%
    left_join(base_n,
      by = join_by(child_id, response_id, ...)
    ) %>%
    tidyr::pivot_wider(
      names_from = item_dominance,
      values_from = response,
      values_fn = sum,
      values_fill = 0,
      id_cols = c(child_id, response_id, type, n_total, te, ...)
    )

  # total vocabulary
  total <- vocab_total(base, ...)
  dominance <- vocab_dominance(base, ...)
  concept <- vocab_concept(base_te, ...)
  te <- vocab_te(base_te, ...)
  contents <- vocab_contents(base, ...)

  # merge all datasets
  vocabulary <- list(total, dominance, concept, te, contents) %>%
    reduce(left_join,
      multiple = "all",
      by = join_by(child_id, response_id, type, ...)
    ) %>%
    mutate(across(
      starts_with("concept|te"),
      function(x) {
        if_else(is.na(x), as.integer(0), x)
      }
    )) %>%
    select(
      child_id, response_id, type, ...,
      matches(paste0(.scale, collapse = "|")),
      contents
    )

  return(vocabulary)
}



#' Check argument `...` in the [bvq::bvq_vocabulary()] function
#'
#' @param x Variable names passed with `...`
#' @param .cols Valid column names
#'
#' @importFrom cli  cli_abort
#' @noRd
check_arg_dots <- function(x, .cols) { # nocov start

  is_valid <- x %in% .cols

  if (!all(is_valid)) {
    which_missing <- x[which(is_valid)]
    cli_msg <- "{.code ...} contains element{?s} {which_missing}, which {?is/are} \
    not a variable in `logs`, `pool`, or `responses`"
    cli_abort(cli_msg)
  }
} # nocov end

#' Compute total vocabulary (L1 + L2)
#'
#' @param x Base data frame from which to calculate total vocabulary size
#'
#' @inheritParams bvq_vocabulary
#'
#' @noRd
#' @keywords internal
#'
vocab_total <- function(x, ...) { # nocov start

  out <- x %>%
    summarise(
      total_count = sum(response, na.rm = TRUE),
      n_total = n(),
      .by = c(child_id, response_id, type, ...)
    ) %>%
    mutate(total_prop = if_else(n_total == 0, 0, total_count / n_total))

  return(out)
} # nocov end

#' Compute dominance vocabulary (L1, L2)
#'
#' @inheritParams bvq_vocabulary
#' @inheritParams vocab_total
#'
#' @noRd
#' @keywords internal
#'
vocab_dominance <- function(x, ...) { # nocov start

  out <- x %>%
    summarise(
      count = sum(response, na.rm = TRUE),
      n_total = sum(!is.na(response)),
      .by = c(child_id, response_id, type, item_dominance, ...)
    ) %>%
    mutate(prop = ifelse(n_total == 0, 0, count / n_total)) %>%
    tidyr::pivot_wider(
      names_from = item_dominance,
      values_from = c(n_total, matches("count|prop")),
      names_glue = "{item_dominance}_{.value}",
      names_repair = janitor::make_clean_names
    ) %>%
    select(
      child_id, response_id, type,
      starts_with("l1_"), starts_with("l2_"),
      -ends_with("n_total"), ...
    )

  return(out)
} # nocov end

#' Compute conceptual vocabulary (L1 or L2)
#'
#' @inheritParams bvq_vocabulary
#' @inheritParams vocab_total
#'
#' @noRd
#' @keywords internal
#'
vocab_concept <- function(x, ...) { # nocov start

  out <- x %>%
    mutate(across(c(L1, L2), function(x) x > 0),
      is_any = rowSums(pick(L2:L1)),
      is_any = is_any > 0
    ) %>%
    summarise(
      n = sum(is_any),
      .by = c(child_id, response_id, type, n_total, ...)
    ) %>%
    rename(concept_count = n) %>%
    mutate(
      concept_count = as.integer(concept_count),
      concept_prop = if_else(n_total == 0, 0, concept_count / n_total)
    ) %>%
    select(child_id, response_id, type, concept_count, concept_prop, ...)

  return(out)
} # nocov end

#' Compute translation equivalent vocabulary (L1 & L2)
#'
#' @inheritParams bvq_vocabulary
#' @inheritParams vocab_total
#'
#' @noRd
#' @keywords internal
#'
vocab_te <- function(x, ...) { # nocov start

  out <- x %>%
    mutate(across(c(L1, L2), function(x) x > 0),
      is_both = rowSums(pick(c(L2, L1))),
      is_both = is_both > 1
    ) %>%
    summarise(
      n = sum(is_both),
      .by = c(child_id, response_id, type, n_total, ...)
    ) %>%
    rename(te_count = n) %>%
    mutate(
      te_count = as.integer(te_count),
      te_prop = if_else(n_total == 0, 0, te_count / n_total)
    )

  return(out)
} # nocov end


#' Gather vocabulary contents
#'
#' @inheritParams bvq_vocabulary
#' @inheritParams vocab_total
#'
#' @noRd
#' @keywords internal
#'
vocab_contents <- function(x, ...) { # nocov start

  out <- x %>%
    dplyr::filter(response) %>%
    summarise(
      contents = list(item[response]),
      .by = c(child_id, response_id, type, ...)
    )

  return(out)
} # nocov end
