#' Generate participant information and progress for each response
#'
#' This function generates a data frame with the vocabulary of each participant
#' (keeping longitudinal data from the same participant in different rows).
#' Comprehensive and productive vocabulary sizes are computed as raw counts
#' (`vocab_count`) and as proportions `vocab_prop`, calculated from the total of
#' items filled by the participant in the response `vocab_n`).
#'
#' @export bvq_vocabulary
#'
#' @import dplyr
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr drop_na
#' @importFrom tidyr pivot_wider
#' @importFrom janitor clean_names
#' @param participants Participants data frame, as generated by
#'   [bvq_participants()]. If `NULL` (default), [bvq_participants()] is run.
#' @param responses Responses data frame, as generated by [bvq_responses()]. If
#'   `NULL` (default), [bvq_responses()] is run.
#' @param .by A character vector that takes the name of the variable(s) to group
#'   data into. Vocabulary metrics will be calculated by aggregating responses
#'   within the groups that result from the combination of crossing of the
#'   variables provided in `.by`. This variables can refer to item properties
#'   (see [pool], e.g., `"category"`) or to participant properties (see
#'   [bvq_logs()], e.g., `"dominance"`).
#' @param scale A character vector that takes the value `"count"` and/or
#'   `"prop"`. If `"count"` (default) vocabulary metrics are reported as counts
#'   (number of words). If `"prop"`, vocabulary metrics are calculated as
#'   proportions?
#' @param ... Extra arguments that will be passed to the `bvq_responses`.
#'   function.
#' @returns A dataset (actually, a [tibble] with each participant's
#'   comprehensive and/or vocabulary size in each language. This data frame
#'   contains the following variables:
#' * id: a character string indicating a participant's identifier. This value is always the same for each participant, so that different responses from the same participant share the same `id`.
#' * time: a numeric value indicating how many times a given participant has been sent the questionnaire, regardless of whether they completed it or not.
#' * age: a numeric value indicating the number of months elapsed since participants' birth date until they filled in the last item of their questionnaire response.
#' * type: a character string indicating the vocabulary type computed: `"understands"` if option "Understands" was selected, and `"produces"` if option "Understands & Says" was selected.
#' * vocab_count_total: integer indicating the number of items selected as "Understands" or "Understands and Says" in both languages.
#' * vocab_count_dominance_l1: positive integer indicating the number of items selected as "Understands" or "Understands and Says" in the dominant language (L1).
#' * vocab_count_dominance_l2: positive integer indicating the number of items selected as "Understands" or "Understands and Says" in the non-dominant language (L2).
#' * vocab_count_conceptual: positive integer indicating the number of translation equivalents (a.k.a. cross-language synonyms or doublets) in which  "at list one of the items was selected as "Understands" or "Understands and Says". This is a measure of the number of lexicalised concepts.
#' * vocab_count_te: positive integer indicating the number of translation equivalents (out of the total number of items the participant answered to) in which at both items was selected as "Understands" or "Understands and Says". This is a measure of the number of lexicalised concepts.
#' * vocab_prop_total: numeric value ranging from 0 to 1 (both included) indicating the proportion of items selected as "Understands" or "Understands and Says" in both languages.
#' * vocab_prop_dominance_l1: numeric value ranging from 0 to 1 (both included) indicating the proportion of of items selected as "Understands" or "Understands and Says" in the dominant language (L1).
#' * vocab_prop_dominance_l2: numeric value ranging from 0 to 1 (both included) indicating the proportion of of items selected as "Understands" or "Understands and Says" in the non-dominant language (L2).
#' * vocab_prop_conceptual: numeric value ranging from 0 to 1 (both included) indicating the proportion of of translation equivalents (a.k.a. cross-language synonyms or doublets) in which at least one of the items was selected as "Understands" or "Understands and Says". This is a measure of the number of lexicalised concepts.
#' * vocab_prop_te: numeric value ranging from 0 to 1 (both included) indicating the proportion of of translation equivalents (aka. cross-language synonyms or doublets) in which both items were selected as "Understands" or "Understands and Says". This is a measure of the number of lexicalised concepts.
#'   The specific subset of columns returned by `bvq_vocabulary` depends on the
#'   arguments provided.
#' @author Gonzalo Garcia-Castro
#' @md
bvq_vocabulary <- function(participants = NULL,
                           responses = NULL,
                           .by = NULL,
                           scale = "count",
                           ...) {
    
    suppressMessages({
        
        bvq_connect() # get credentials to Google and formr
        
        if (!any(scale %in% c("count", "prop"))) {
            stop("Argument scale must be \'count\' and/or \'prop\'")
        }
        
        if (is.null(responses)) {
            if (is.null(participants)) participants <- bvq_participants()
            responses <- bvq_responses()
        }
        
        logs <- bvq_logs(participants, responses) %>%
            filter(id %in% unique(responses$id)) # get logs
        
        vocab_base <- responses %>%
            mutate(understands = response==2|response==3,
                   produces = response==3) %>% 
            select(-response) %>%
            pivot_longer(c(understands, produces), 
                         names_to = "type", 
                         values_to = "response") %>%
            drop_na(response) %>%
            left_join(select(pool, any_of(c("item", "te", "language", .by))),
                      by = join_by(language, item),
                      multiple = "all") %>%
            left_join(select(logs, any_of(c("id", "time", .by))),
                      by = join_by(id, time),
                      multiple = "all") %>%
            mutate(item_dominance = ifelse(language==dominance, "L1", "L2")) %>%
            select(any_of(c("id", "time", "age", "item_dominance", "type", "te", 
                            "item", .by, "response")))
        
        # total vocabulary
        vocab_total <- vocab_base %>%
            group_by_at(c("id", "time", "age", "type", .by)) %>%
            summarise(vocab_count_total = sum(response, na.rm = TRUE),
                      vocab_n_total = n(),
                      .groups = "drop") %>%
            mutate(vocab_prop_total = ifelse(vocab_n_total==0,
                                             0, 
                                             vocab_count_total/vocab_n_total))
        
        # total vocabulary in Catalan
        vocab_total_dominance <- vocab_base %>%
            group_by_at(c("id", "time", "age", "type", "item_dominance", .by), .drop = FALSE) %>%
            summarise(vocab_count_dominance = sum(response, na.rm = TRUE),
                      n_total = sum(!is.na(response)),
                      .groups = "drop") %>%
            mutate(vocab_prop_dominance = ifelse(n_total==0, 
                                                 0, 
                                                 vocab_count_dominance/n_total)) %>%
            pivot_wider(names_from = item_dominance,
                        values_from = c(n_total, matches("vocab"))) %>%
            clean_names() %>%
            select(id, time, age, type, 
                   starts_with("vocab_count"), 
                   starts_with("vocab_prop"),
                   any_of(.by))
        
        # conceptual vocabulary
        n_total <- vocab_base %>%
            distinct_at(c("id", "time", "age", "te", .by)) %>%
            group_by_at(c("id", "time", "age", .by), .drop = FALSE) %>%
            mutate(n_total = n()) %>%
            ungroup() %>%
            select_at(c("id", "time", "te", .by, "n_total"))
        
        vocab_conceptual <- vocab_base %>%
            left_join(n_total,
                      by = join_by(id, time, te),
                      multiple = "all") %>%
            filter(response) %>%
            group_by_at(c("id", "time", "age", "type", "te", "n_total", .by), .drop = FALSE) %>%
            summarise(n = n(), .groups = "drop") %>%
            group_by_at(c("id", "time", "type", "age", "n_total", .by), .drop = FALSE) %>%
            summarise(n = n(), .groups = "drop")  %>%
            rename(vocab_count_conceptual = n) %>%
            mutate(vocab_count_conceptual = as.integer(vocab_count_conceptual),
                   vocab_prop_conceptual = vocab_count_conceptual/n_total) %>%
            select(id, time, age, type, 
                   starts_with("vocab_count"), 
                   starts_with("vocab_prop"), 
                   any_of(.by))
        
        # TE vocabulary
        vocab_te <- vocab_base %>%
            left_join(n_total,
                      by = join_by(id, time, te),
                      multiple = "all") %>%
            filter(response) %>%
            group_by_at(c("id", "time", "age", "type", "te", "n_total", .by), .drop = FALSE) %>%
            summarise(n = n(), .groups = "drop") %>%
            filter(n > 1) %>%
            group_by_at(c("id", "time", "age", "type", "n_total", .by), .drop = FALSE) %>%
            summarise(n = n(), .groups = "drop") %>%
            rename(vocab_count_te = n) %>%
            mutate(vocab_prop_te = vocab_count_te/n_total,
                   vocab_count_te = as.integer(vocab_count_te)) %>%
            select(id, time, age, type,
                   starts_with("vocab_count"),
                   starts_with("vocab_prop"),
                   any_of(.by))
        
        # merge all datasets
        vocabulary <- list(vocab_total, vocab_total_dominance, vocab_conceptual, vocab_te) %>% 
            reduce(left_join,
                   by = c("id", "time", "age", "type", .by),
                   multiple = "all") %>%
            mutate(across(matches("conceptual|te"), 
                          \(x) ifelse(is.na(x), as.integer(0), x))) %>%
            select_at(vars(one_of("id", "time", "age", "type", .by), 
                           matches(scale))) %>%
            arrange(desc(id), time, type)
        
    })
    
    return(vocabulary)
    
}

