#' Generate participant information and progress for each response
#'
#' This function generates a data frame with the vocabulary of each participant
#' (keeping longitudinal data from the same participant in different rows).
#' Comprehensive and productive vocabulary sizes are computed as raw counts
#' (`vocab_count`) and as proportions `vocab_prop`, calculated from the total of
#' items filled by the participant in the response `vocab_n`).
#'
#' @export bvq_vocabulary
#'
#' @import dplyr
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr drop_na
#' @importFrom tidyr pivot_wider
#' @importFrom janitor clean_names
#' @importFrom janitor make_clean_names
#' @param participants Participants data frame, as generated by [bvq::bvq_participants()].
#' @param responses Responses data frame, as generated by [bvq::bvq_responses()].
#' @param .by A character vector that takes the name of the variable(s) to group
#'   data into. Vocabulary metrics will be calculated by aggregating responses
#'   within the groups that result from the combination of crossing of the
#'   variables provided in `.by`. This variables can refer to item properties
#'   (see [bvqdev::pool], e.g., `"category"`) or to participant properties (see
#'   [bvq_logs()], e.g., `"dominance"`).
#' @param .scale A character vector that takes the value `"count"` and/or
#'   `"prop"`. If `"prop"` (default), vocabulary metrics are calculated as
#'   proportions. If `"count"`, vocabulary metrics are reported as counts
#'   (number of words). 
#' @param ... Extra arguments that will be passed to the `bvq_responses`.
#'   function.
#' @returns A dataset (actually, a [tibble::tibble] with each participant's
#'   comprehensive and/or vocabulary size in each language. This data frame
#'   contains the following variables:
#' * id: a character string with five digits indicating a participant's identifier in the database from the [Laboratori de Recerca en Infància](https://www.upf.edu/web/cbclab) at Universitat Pompeu Fabra. This value is always the same for each participant, so that different responses from the same participant share the same `id`.
#' * time: a numeric value indicating how many times a given participant has been sent the questionnaire, regardless of whether they completed it or not.
#' * age: a numeric value indicating the number of months elapsed since participants' birth date until they filled in the last item of their questionnaire response.
#' * type: a character string indicating the vocabulary type computed: `"understands"` if option "Understands" was selected, and `"produces"` if option "Understands & Says" was selected.
#' * total_count: integer indicating the number of items selected as "Understands" or "Understands and Says" in both languages.
#' * l1_count: positive integer indicating the number of items selected as "Understands" or "Understands and Says" in the dominant language (L1).
#' * l2_count: positive integer indicating the number of items selected as "Understands" or "Understands and Says" in the non-dominant language (L2).
#' * concept_count: positive integer indicating the number of translation equivalents (a.k.a. cross-language synonyms or doublets) in which  "at list one of the items was selected as "Understands" or "Understands and Says". This is a measure of the number of lexicalised concepts.
#' * te_count: positive integer indicating the number of translation equivalents (out of the total number of items the participant answered to) in which at both items was selected as "Understands" or "Understands and Says". This is a measure of the number of lexicalised concepts.
#' * total_prop: numeric value ranging from 0 to 1 (both included) indicating the proportion of items selected as "Understands" or "Understands and Says" in both languages.
#' * l1_prop: numeric value ranging from 0 to 1 (both included) indicating the proportion of of items selected as "Understands" or "Understands and Says" in the dominant language (L1).
#' * l2_prop: numeric value ranging from 0 to 1 (both included) indicating the proportion of of items selected as "Understands" or "Understands and Says" in the non-dominant language (L2).
#' * concept_prop: numeric value ranging from 0 to 1 (both included) indicating the proportion of of translation equivalents (a.k.a. cross-language synonyms or doublets) in which at least one of the items was selected as "Understands" or "Understands and Says". This is a measure of the number of lexicalised concepts.
#' * te_prop: numeric value ranging from 0 to 1 (both included) indicating the proportion of of translation equivalents (aka. cross-language synonyms or doublets) in which both items were selected as "Understands" or "Understands and Says". This is a measure of the number of lexicalised concepts.
#'   The specific subset of columns returned by `bvq_vocabulary` depends on the elements of `.by` and `.scale`.
#' @author Gonzalo Garcia-Castro
#' @md
bvq_vocabulary <- function(participants,
                           responses,
                           .by = NULL,
                           .scale = "prop",
                           ...) {
    
    suppressMessages({
        
        if (!any(.scale %in% c("count", "prop"))) {
            cli_abort("Argument .scale must be 'count' and/or 'prop'")
        }
        
        # check if all .by are colnames
        is_by_colname <- .by %in% c(colnames(participants), colnames(responses))
        if (!all(is_by_colname)) {
            which_missing <- .by[which(is_by_colname)]
            cli_msg <- "`.by` contains element {which_missing}, which is not
                        a variable in `participants` or `responses`"
            cli_abort(cli_msg)
        }
        
        # get logs
        logs <- bvq_logs(participants, responses) %>%
            filter(id %in% unique(responses$id)) 
        
        # get main dataset
        vocab_base <- responses %>%
            mutate(understands = response > 1,
                   produces = response > 2) %>% 
            select(-response) %>%
            pivot_longer(c(understands, produces), 
                         names_to = "type", 
                         values_to = "response") %>%
            drop_na(response) %>%
            inner_join(select(bvq::pool, any_of(c("item", "te", "language", .by))),
                       multiple = "all",
                       by = join_by(item),
                       relationship = "many-to-many") %>%
            inner_join(select(logs, any_of(c("id", "time", "dominance", .by))),
                       multiple = "all",
                       by = join_by(id, time),
                       relationship = "many-to-many") %>%
            mutate(item_dominance = ifelse(language==dominance, "L1", "L2")) %>%
            select(any_of(c("id", "time", "dominance", "item_dominance", "type", 
                            "te", "item", .by, "response")))
        
        # total vocabulary
        vocab_total <- vocab_base %>%
            summarise(total_count = sum(response, na.rm = TRUE),
                      n_total = n(),
                      .by = any_of(c("id", "time", "age", "type", .by))) %>%
            mutate(total_prop = ifelse(n_total==0, 0, total_count/n_total))
        
        # total vocabulary in Catalan
        vocab_total_dominance <- vocab_base %>%
            summarise(count = sum(response, na.rm = TRUE),
                      n_total = sum(!is.na(response)),
                      .by = any_of(c("id", "time", "type", "item_dominance", .by))) %>%
            mutate(prop = ifelse(n_total==0, 0, count/n_total)) %>%
            pivot_wider(names_from = item_dominance,
                        values_from = c(n_total, matches("count|prop")),
                        names_glue = "{item_dominance}_{.value}",
                        names_repair = make_clean_names) %>% 
            clean_names() %>%
            select(id, time, type,
                   starts_with("l1_"), 
                   starts_with("l2_"), 
                   -ends_with("n_total"),
                   any_of(.by))
        
        # conceptual vocabulary
        n_total <- vocab_base %>%
            distinct(pick(any_of(c("id", "time", "te", .by)))) %>%
            count(pick(any_of(c("id", "time", .by))),
                  name = "n_total") %>% 
            select(any_of(c("id", "time", .by, "n_total")))
        
        vocab_by_te_base <- vocab_base %>%
            filter(response) %>% 
            left_join(n_total, 
                      multiple = "all", 
                      by = join_by(id, time)) %>%
            pivot_wider(names_from = item_dominance,
                        values_from = response,
                        values_fn = sum,
                        values_fill = 0,
                        id_cols = any_of(c("id", "time", "type", "n_total", "te", .by)))
        
        vocab_conceptual <- vocab_by_te_base %>% 
            mutate(across(c(L1, L2), function(x) x > 0),
                   is_any = rowSums(pick(L2:L1)),
                   is_any = is_any > 0) %>% 
            summarise(n = sum(is_any), 
                      .by = any_of(c("id", "time", "type", "n_total", .by))) %>%
            rename(concept_count = n) %>%
            mutate(concept_count = as.integer(concept_count),
                   concept_prop = ifelse(n_total==0, 0, concept_count/n_total)) %>%
            select(id, time, type, concept_count, concept_prop, any_of(.by))

        # TE vocabulary
        vocab_te <- vocab_by_te_base %>%
            mutate(across(c(L1, L2), function(x) x > 0),
                   is_both = rowSums(pick(c(L2, L1))),
                   is_both = is_both > 1) %>% 
            summarise(n = sum(is_both), 
                      .by = any_of(c("id", "time", "type", "n_total", .by))) %>%
            rename(te_count = n) %>%
            mutate(te_count = as.integer(te_count),
                   te_prop = ifelse(n_total==0, 0, te_count/n_total)) %>%
            select(id, time, type, te_count, te_prop, any_of(.by))
            
        
        # merge all datasets
        which_col_not <- c("count", "prop")[which(!(c("count", "prop") %in% .scale))]
        
        vocabulary <- list(vocab_total, vocab_total_dominance, vocab_conceptual, vocab_te) %>% 
            reduce(left_join,
                   multiple = "all", 
                   by = join_by(id, time, type)) %>%
            mutate(across(matches("concept|te"), 
                          function(x) ifelse(is.na(x), as.integer(0), x))) %>%
            select(any_of(c("id", "time", "age", "type", .by)), matches(.scale)) %>%
            select(-ends_with(which_col_not))
        
        return(vocabulary)
        
    })
}
